/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package process;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Process extends javax.swing.JFrame {

    /**
     * Creates new form Process
     */
    private boolean off=false;
    public Process() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btmStart = new javax.swing.JButton();
        btmStop = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("PROCESS PROGRAM");

        btmStart.setText("Start");
        btmStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btmStartMouseClicked(evt);
            }
        });
        btmStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmStartActionPerformed(evt);
            }
        });

        btmStop.setText("Stop");
        btmStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btmStopMouseClicked(evt);
            }
        });
        btmStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmStopActionPerformed(evt);
            }
        });

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btmStart, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(btmStop, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btmStop, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(btmStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmStartActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_btmStartActionPerformed

    private void btmStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmStopActionPerformed
        // TODO add your handling code here:
      

    }//GEN-LAST:event_btmStopActionPerformed

    private void btmStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmStartMouseClicked
        try {
            // TODO add your handling code here:

            ArbolBB(Integer.parseInt(JOptionPane.showInputDialog("Ingrese cuantos proceso desea realizar")));
        } catch (InterruptedException ex) {
            Logger.getLogger(Process.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btmStartMouseClicked

    private void btmStopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmStopMouseClicked
        // TODO add your handling code here:
          off =true;
    }//GEN-LAST:event_btmStopMouseClicked

    //***************************************************************START*******************************************************+
    void ArbolBB(int n) throws InterruptedException{
        ArbolAVL tree = new ArbolAVL();
        
        int count =0, priori=0;
        String pid="";
        float time=0;
            while (count <n) {
            
            if(off==true)
                break;
           
            if(count<=8){
                if(count==0)
                    txtArea.append("*****************CREANDO PROCESOS*********************\n");
                
                pid=PID();
                priori=Priori();
                time=Xtime();
                
                txtArea.append("-> "+(count)+" | Estado (nuevo)| Proceso :"+pid+ "| Prioridad : "+ priori+ "| Tiempo E. :"+time+"| \n ");
                tree.insertarProceso(pid,priori,time);
                
                //Thread.sleep(2000);
            }else{
               
                tree.insertarProceso(PID(),Priori(), Xtime());
                txtArea.append("->  "+count+" | Estado (nuevo) | Proceso :"+pid+ "| Prioridad : "+ priori+ "| Tiempo E. :"+time+"|\n ");
                Nodo prior = tree.getMasPrioritario(tree.getRaiz()); 
                txtArea.append("---->| Estado (listo)| Proceso : "+prior.getPID()+"| Prioridad : "+prior.getKey()+ "| Tiempo E. :"+ prior.getTime()+"| \n");
                tree.imprimirMasPrioritario();
                System.out.println("INorder");
                tree.imprimirInorder();
                txtArea.append("---->| Estado (ejecutando)| Proceso : "+prior.getPID()+"| Prioridad : "+prior.getKey()+ "| Tiempo E. :"+ prior.getTime()+"| \n");
                txtArea.append("---->| Estado (terminado)| Proceso : "+prior.getPID()+"| Prioridad : "+prior.getKey()+ "| Tiempo E. :"+ prior.getTime()+"| \n");
                
                prioridad(tree);
            }
 
            count++;
        }
        /* The AVL Tree after deletion of 10
           1
          /  \
         0    9
        /     / \
        -1    5   11
        /  \
        2    6
         */
        /*System.out.println("");
        System.out.println("Preorder traversal after "+
                           "deletion of 10 :");*/
       // tree.ImprimiPreOrder();
       /* Nodo temp = tree.masPrioritario(); 
        System.out.println("nodo mas prioritario");
        System.out.println(temp.getKey());
        
        tree.imprimiPreOrder();
        System.out.println("nodos  mas prioritario");
        tree.imprimirMasPrioritario();
        
        */
       
      
       
    }
    public void prioridad(ArbolAVL tree){
        
       
       System.out.println("tranversal ");
       System.out.println("\n");
       
       System.out.println("\n");
       tree.limpiarTemp();
       tree.actualizarFlag();
       Nodo prior2= tree.getMasPrioritario(tree.getRaiz());
       System.out.println("mas prior1 "+prior2.getKey());
       tree.imprimirMasPrioritario();

    }
    
    
    public static String PID(){
    return String.valueOf((int) (Math.random()*2000+1) + (int) (Math.random()*2000+1) );
    }
    public static int Priori() {
      return ((int) (Math.random()*100) + (int) (Math.random()*100));
    }
    public static float Xtime(){
      return (float) (Math.random()*20 + (int) (Math.random()*100)); 
    }



    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Process.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Process.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Process.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Process.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Process().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmStart;
    private javax.swing.JButton btmStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
